version: '3.2'

services:
  db:
    image: postgres:15.0
    networks:
      - app-tier
    ports:
      - "5431:5431"
    environment:
      POSTGRES_PASSWORD: 76d059610f5b
      POSTGRES_USER: postgres
      PGPORT: 5432

  redis:
    image: redis:7.0.5
    networks:
      - app-tier
    ports:
      - '6379:6379'

  gate:
    build:
      context: ./
      dockerfile: ./microservices/gate/dockerfile
    ports:
      - '0:40000'
    depends_on:
      - redis
      - auth
      - user
    networks:
      - app-tier
  auth:
    build:
      context: ./
      dockerfile: ./microservices/auth/dockerfile
    depends_on:
      - redis
    networks:
      - app-tier

  user:
    build:
      context: ./
      dockerfile: ./microservices/user/dockerfile
    depends_on:
      - redis
      - db
    networks:
      - app-tier
    environment:
      POSTGRES_PASSWORD: abcde
      POSTGRES_USER: postgres
      PGPORT: 5431

  api-tests:
    build:
      context: ./
      dockerfile: ./tests/test-api/dockerfile
    depends_on:
      - gate
    networks:
      - app-tier

networks:
  app-tier:
    ipam:
      config:
        - subnet: 172.17.0.0/16
