FROM haskell:9.0.2



ENV REDIS_HOST redis
ENV REDIS_PORT 6379

COPY ./microservices/user/ /user
COPY ./lib                 /app-lib/

RUN       cd user && stack install --dependencies-only --stack-yaml ./stack-docker.yaml
RUN       cd user && stack install --stack-yaml ./stack-docker.yaml
CMD       cd user && stack run     --stack-yaml ./stack-docker.yaml


