name:                auth
version:             0.1.0.0
github:              "githubuser/auth"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"
description:         Please see the README on GitHub at <https://github.com/githubuser/auth#readme>
dependencies:
- base >= 4.7 && < 5
- bytestring
- cryptonite
- aeson
- text
- binary
- lib
- mtl
- hedis
- uuid
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints


library:
  source-dirs: src
executables:
  auth-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - auth
tests:
  auth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - auth
